### ISSUE TITLE
Total Peers counter shows -1

### ISSUE THREAD

**Issue by rymuff** [web3labs/epirus-free#44]
'Total Peers' counter in dashboard always shows `-1`.
Also, 'Network' page responses `The server responded with an error code: 500.`.

**Comment by SweeXordious** [comment]
This means that Epirus is not connected to your node, most likely.
Did you setup the `endpoint` before running it? 
Also, is the node accessible from inside the container?
Also,when you started Epirus, did it show a message that it is being setup for some time? Or it moved straight to the home page? 
Please provide more information about your setup so that we can help you.

**Comment by rymuff** [comment]
> This means that Epirus is not connected to your node, most likely. Did you setup the `endpoint` before running it? Also, is the node accessible from inside the container? Also,when you started Epirus, did it show a message that it is being setup for some time? Or it moved straight to the home page? Please provide more information about your setup so that we can help you.

Yes, I setup local node with `geth <...> --http --http.api eth,net,web3 --http.addr 0.0.0.0 --http.corsdomain '*'`,
and run with `NODE_ENDPOINT=http://172.16.239.1:8545 docker-compose up`.
However, I realized local node should have `admin` api, and now it works well!

Is there any requirement for which api should be provided?
